var e;function h(a,b){function c(){}c.prototype=b.prototype;a.bb=b.prototype;a.prototype=new c;a.xd=function(a,c,g){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};var l={},m,p={},q={};p.qc=function(){!0===r&&(JSON.parse(window.localStorage.getItem("me.save"))||[]).forEach(function(a){q[a]=JSON.parse(window.localStorage.getItem("me.save."+a))})};p.add=function(a){Object.keys(a).forEach(function(b){"add"!==b&&"delete"!==b&&(function(a){Object.defineProperty(p,a,{enumerable:!0,get:function(){return q[a]},set:function(b){"object"!==typeof q[a]&&(q[a]=b,!0===r&&window.localStorage.setItem("me.save."+a,JSON.stringify(q[a])))}})}(b),b in q||(p[b]=a[b]))})};
p["delete"]=function(a){"add"!==a&&"delete"!==a&&"undefined"!==typeof q[a]&&(delete q[a],!0===r&&window.localStorage.removeItem("me.save."+a))};function t(a,b,c){null===this.pos&&(this.pos=new u);v(this.pos,a);null===this.offset&&(this.offset=new u);this.offset.set(0,0);null===this.R&&(this.R=new u);v(this.R,0);this.width=b;this.height=c;Object.defineProperty(this,"left",{get:function(){return this.pos.x},configurable:!0});Object.defineProperty(this,"right",{get:function(){return this.pos.x+this.width},configurable:!0});Object.defineProperty(this,"top",{get:function(){return this.pos.y},configurable:!0});Object.defineProperty(this,"bottom",
{get:function(){return this.pos.y+this.height},configurable:!0})}e=t.prototype;e.pos=null;e.R=null;e.width=0;e.height=0;e.Zc="Rectangle";e.offset=null;e.set=function(a,b,c){v(this.pos,a);this.width=b;this.height=c;this.offset.set(0,0)};e.Sa=function(){return this.Oa()};e.Oa=function(){return new t(this.pos.Oa(),this.width,this.height)};e.translate=function(a,b){this.pos.x+=a;this.pos.y+=b;return this};e.J=function(a){this.R.x=a-this.width-this.R.x};e.K=function(a){this.R.y=a-this.height-this.R.y};
e.contains=function(a){return a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom};e.i=function(a,b){a.strokeStyle=b||"red";a.strokeRect(this.left,this.top,this.width,this.height)};function w(a,b,c){t.call(this,a,b,c);null===this.s&&(this.s=new u);this.s.set(0.5,0.5);x(this,1)}h(w,t);e=w.prototype;e.Pb=!0;e.visible=!0;e.Aa=!1;e.Gb=!1;e.gd=!1;e.Wa=!1;e.xa=!1;e.z=0;e.s=null;e.alpha=1;function x(a,b){"number"===typeof b&&(a.alpha=b.Q(0,1),a.alpha!==a.alpha&&(a.alpha=1))}e.update=function(){return!1};e.i=function(a,b){w.bb.i.call(this,a,b)};function y(a,b,c,d,f){w.call(this,new u(a,b),d||c.width,f||c.height);this.e=c;this.scale=new u(1,1);this.Ka=this.X=this.Y=!1;this.offset=new u(0,0);this.visible=!0;this.ha=this.Wa=!1}h(y,w);e=y.prototype;e.scale=null;e.Ka=!1;e.X=!1;e.Y=!1;e.z=0;e.offset=null;e.Na=0;e.hb=0;e.e=null;e.ha=!1;e.wa=-1;e.Qa=null;e.kb=!1;e.J=function(a){a!==this.X&&(this.X=a,this.scale.x=-this.scale.x,this.Ka=1!==this.scale.x||1!==this.scale.y)};
e.K=function(a){a!==this.Y&&(this.Y=a,this.scale.y=-this.scale.y,this.Ka=1!==this.scale.x||1!==this.scale.y)};e.update=function(){return this.ha?(this.wa-=aa,0>this.wa&&(this.Qa&&this.Qa(),this.wa=-1,0>this.wa?(this.ha=!1,this.Qa=null):this.ha||(this.Qa=void 0,this.ha=!0)),!0):!1};
e.i=function(a){if(this.ha&&(this.kb=!this.kb,!this.kb))return;a.save();a.globalAlpha*=this.alpha;var b=~~this.pos.x,c=~~this.pos.y,d=this.width,f=this.height,g=this.Na+this.hb;if(this.Ka||0!==g){var k=d*this.s.x,n=f*this.s.y;a.translate(b+k,c+n);this.Ka&&a.scale(this.scale.x,this.scale.y);0!==g&&a.rotate(g);0!==this.hb?(d=this.height,f=this.width,b=-n,c=-k):(b=-k,c=-n)}a.drawImage(this.e,this.offset.x,this.offset.y,d,f,b,c,d,f);a.restore()};e.H=function(){this.ma.apply(this,arguments)};e.ma=function(){};function z(a,b,c,d,f,g,k,n,s){y.call(this,a,b,c,d,f);this.G={};this.l=this.pa=null;this.sa=100;this.t=g||0;this.margin=k||0;this.ib=this.qa=null;a=n||void 0;s=s||void 0;if(void 0!==a)this.qa=a,this.ib=s;else for(this.qa=[],s=new u(~~((this.e.width-this.margin)/(this.width+this.t)),~~((this.e.height-this.margin)/(this.height+this.t))),a=0,b=s.x*s.y;a<b;a++)this.qa[a]={name:""+a,offset:new u(this.margin+a%s.x*(this.t+this.width),this.margin+(this.t+this.height)*~~(a/s.x)),width:this.width,height:this.height,
Na:0};ba(this);ca(this,"default")}h(z,y);e=z.prototype;e.G={};e.t=0;e.margin=0;e.sc=!1;e.sa=100;
function ba(a){var b=null;debugger;a.G["default"]={name:"default",frame:[],S:0,length:0,sa:a.sa,rb:0};if(null==b){var b=[],c=0;a.qa.forEach(function(){b[c]=c++})}for(var d=0,f=b.length;d<f;d++)if("number"===typeof b[d])a.G["default"].frame[d]=a.qa[b[d]];else{if(null===a.ib)throw"melonjs: string parameters for addAnimation are only allowed for TextureAtlas ";a.G["default"].frame[d]=a.qa[a.ib[b[d]]]}a.G["default"].length=a.G["default"].frame.length}
function ca(a,b){if(a.G[b])a.l=a.G[b],a.pa=null,da(a,a.l.S),a.l.rb=A+a.l.sa;else throw"melonJS: animation id '"+b+"' not defined";}function da(a,b){a.l.S=(b||0)%a.l.length;var c=a.l.frame[a.l.S];a.offset=c.offset;a.width=c.width;a.height=c.height;a.hb=c.Na}
e.update=function(){if(!this.sc&&A>=this.l.rb){da(this,++this.l.S);if(0===this.l.S&&this.pa)if("string"===typeof this.pa)ca(this,this.pa);else if("function"===typeof this.pa&&!1===this.pa())return this.l.S=this.l.length-1,da(this,this.l.S),z.bb.update.call(this),!1;this.l.rb=A+this.l.sa;return z.bb.update.call(this)||!0}return z.bb.update.call(this)};function B(a,b,c){null===this.pos&&(this.pos=new u);w.call(this,this.pos.set(a,b),~~c.Yb||~~c.width,~~c.$c||~~c.height);c.e&&(this.g=new z(0,0,"string"===typeof c.e?C.Ta(c.e):c.e,~~c.Yb,~~c.$c,~~c.t,~~c.margin),c.cd&&(a=this.g,b=c.cd,b="#"===b.charAt(0)?b.substring(1,7):b,a.e=l.h.tc(a.e,"transparent",b.toUpperCase()).canvas));ea++;this.name=c.name?c.name.toLowerCase():"";void 0===this.bc&&(this.bc=new u);this.bc.set(0,0);void 0===this.Eb&&(this.Eb=new u);this.Eb.set(0,0);void 0===this.Mb&&(this.Mb=
new u);this.Mb.set(0,0);void 0===this.Sb&&(this.Sb=new u);this.Sb.set(1E3,1E3);this.visible=this.Ec=!0;this.Wa=this.xa=!1;this.da="undefined"!==typeof c.da?c.da:!0;this.type=c.type||0;this.X=this.Y=!1;this.va=E.va;!0===c.Va?fa(this,new l.md(new u(0,0),this.width,this.height)):!0===c.ja||!0===c.Ba?(fa(this,new l.sd(new u(0,0),c.Ha,c.ja)),this.width=this.w.width,this.height=this.w.height):fa(this,new t(new u(0,0),this.width,this.height))}h(B,w);e=B.prototype;e.type=0;e.da=!0;e.w=null;e.aa=null;
e.g=null;e.X=!1;e.Y=!1;function fa(a,b){null===a.aa&&(a.aa=[]);a.aa.push(b);1===a.aa.length&&(a.w=a.aa[0].Sa(),a.w.pos=a.pos,a.pos.add(a.aa[0].offset))}e.Tb=function(){this.da&&this.type===E.zb&&E.remove(this)};e.J=function(a){a!==this.X&&(this.X=a,this.g&&this.g.J&&this.g.J(a),this.w.J(this.width))};e.K=function(a){a!==this.Y&&(this.Y=a,this.g&&this.g.K&&this.g.K(a),this.w.K(this.height))};e.Pa=function(a){return E.Pa(this,a||!1)};e.ea=function(a,b){return E.ea(this,a,b||!1)};
e.update=function(){return this.g?this.g.update():!1};e.Sa=function(){var a;this.g?(a=this.g.Sa(),a.pos.add(this.pos)):a=null;return a};e.i=function(a){if(this.g){var b=~~(this.pos.x+this.s.x*(this.width-this.g.width)),c=~~(this.pos.y+this.s.y*(this.height-this.g.height));a.translate(b,c);this.g.i(a);a.translate(-b,-c)}};e.H=function(){this.g&&(this.g.H.apply(this.g,arguments),this.g=null);this.ma.apply(this,arguments);this.w=null;this.aa=[]};e.ma=function(){};function ga(a,b,c){B.call(this,a,b,c);this.Kc=c.yb;this.fade=c.fade;this.duration=c.duration;this.Kb=!1;this.nb=c.yb}h(ga,B);ga.prototype.Lc=function(){ha(this.nb);E.viewport.fadeOut(this.fade,this.duration)};ga.prototype.Tb=function(){this.nb=this.Kc;this.fade&&this.duration?this.Kb||(this.Kb=!0,E.viewport.fadeIn(this.fade,this.duration,this.Lc.bind(this))):ha(this.nb)};function ia(a,b,c){B.call(this,a,b,c);this.type=E.zb}h(ia,B);var F={};function ja(a,b){F[a.toLowerCase()]={"class":b,pool:void 0}}
function ka(a){var b="string"===typeof a?a.toLowerCase():void 0;if(b&&F[b]){var c;if(!F[b].pool)return c=F[b]["class"],arguments[0]=c,new (c.bind.apply(c,arguments));var d=F[b];c=d["class"];0<d.pool.length?(c=d.pool.pop(),c.Dc.apply(c,Array.prototype.slice.call(arguments,1))):(arguments[0]=c,c=new (c.bind.apply(c,arguments)),c.className=b);d.active.push(c);return c}if((d=arguments[3])&&d.M&&d.e)return new y(d.x,d.y,d.e);b&&console.error("Cannot instantiate entity of type '"+a+"': Class not found!");
return null};var la=!0;function ma(a,b){w.call(this,new u(0,0),0,0);this.Wa=(this.Fb=this.visible=!0===a||!1)&&!0===b||!1}h(ma,w);e=ma.prototype;e.Fb=!1;e.visible=!1;e.frame=0;e.z=999;e.reset=function(){E.reset();this.frame=0;this.Vb.apply(this,arguments);this.Fb&&(this.xa=this.visible=!0,this.set(new u,E.viewport.width,E.viewport.height),E.add(this,this.z));E.sort()};e.H=function(){this.ma.apply(this,arguments)};e.update=function(){return!1};e.i=function(){};e.Vb=function(){};e.ma=function(){};function na(){ma.call(this,!0);this.pb=!1;this.handle=null}h(na,ma);e=na.prototype;e.Vb=function(){this.Za=new l.ec("century gothic",32,"white","middle");this.Fa=new l.ec("century gothic",32,"#55aa00","middle");this.Za.textBaseline=this.Fa.textBaseline="alphabetic";this.ua=4;this.handle=l.event.ad(l.event.gc,this.Nc.bind(this));this.Rb=0};e.ma=function(){this.Za=this.Fa=null;this.handle&&(l.event.ed(this.handle),this.handle=null)};e.Nc=function(a){this.Rb=a;this.pb=!0};
e.update=function(){return!0===this.pb?(this.pb=!1,!0):!1};
e.i=function(a){var b=this.Za.measureText(a,"melon").width,c=(l.h.width-b-this.Fa.measureText(a,"JS").width)/2,d=l.h.height/2+this.Fa.measureText(a,"melon").height;l.h.Ib(a,"#202020");var f=l.h.height/2-this.ua/2-90,g=(l.h.width-100)/2;a.save();a.translate(g,f);a.beginPath();a.moveTo(0.7,48.9);a.bezierCurveTo(10.8,68.9,38.4,75.8,62.2,64.5);a.bezierCurveTo(86.1,53.1,97.2,27.7,87,7.7);a.lineTo(87,7.7);a.bezierCurveTo(89.9,15.4,73.9,30.2,50.5,41.4);a.bezierCurveTo(27.1,52.5,5.2,55.8,0.7,48.9);a.lineTo(0.7,
48.9);a.lineTo(0.7,48.9);a.closePath();a.fillStyle="rgb(255, 255, 255)";a.fill();a.beginPath();a.moveTo(84,7);a.bezierCurveTo(87.6,14.7,72.5,30.2,50.2,41.6);a.bezierCurveTo(27.9,53,6.9,55.9,3.2,48.2);a.bezierCurveTo(-0.5,40.4,14.6,24.9,36.9,13.5);a.bezierCurveTo(59.2,2.2,80.3,-0.8,84,7);a.lineTo(84,7);a.closePath();a.lineWidth=5.3;a.strokeStyle="rgb(255, 255, 255)";a.lineJoin="miter";a.miterLimit=4;a.stroke();a.restore();this.Za.i(a,"melon",c,d);this.Fa.i(a,"JS",c+b,d);b=Math.floor(this.Rb*l.h.width);
a.fillStyle="black";a.fillRect(0,l.h.height/2-this.ua/2,l.h.width,this.ua);a.fillStyle="#55aa00";a.fillRect(2,l.h.height/2-this.ua/2,b,this.ua)};function u(a,b){this.x=a||0;this.y=b||0}e=u.prototype;e.x=0;e.y=0;e.set=function(a,b){this.x=a;this.y=b;return this};function v(a,b){a.x=b.x;a.y=b.y}e.add=function(a){this.x+=a.x;this.y+=a.y;return this};e.scale=function(a){this.x*=a.x;this.y*=a.y;return this};e.Q=function(a,b){return new u(this.x.Q(a,b),this.y.Q(a,b))};e.floor=function(){return new u(~~this.x,~~this.y)};e.ceil=function(){return new u(Math.ceil(this.x),Math.ceil(this.y))};
e.length=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};e.Na=function(a){return Math.atan2(a.y-this.y,a.x-this.x)};e.Oa=function(){return new u(this.x,this.y)};e.toString=function(){return"x:"+this.x+",y:"+this.y};var G=new t(new u,0,0),oa=0;function H(a,b,c,d){w.call(this,new u(a||0,b||0),c||Infinity,d||Infinity);this.children=[];this.ab=E.ab;this.ca=!0}h(H,w);e=H.prototype;e.ab="z";e.ca=!0;e.na=null;e.children=null;e.da=!0;function pa(a,b){"undefined"!==typeof b.C&&b.C.removeChild(b);b.C=a;a.children.push(b);!0===a.ca&&a.sort()}
e.ya=function(a,b){for(var c=[],d=RegExp(b,"i"),f=this.children.length,g;f--,g=this.children[f];)g instanceof H?c=c.concat(g.ya(a,b)):g.Ec&&("string"===typeof g[a]?g[a].match(d)&&c.push(g):g[a]===b&&c.push(g));return c};
e.removeChild=function(a,b){if(this===a.C){a.C=void 0;if(!b){"function"===typeof a.H&&a.H();var c=a.className;if(c&&F[c]){for(var d=!0,f=0,g=F[c].active.length;f<g;f++)if(F[c].active[f]===a){d=!1;F[c].active.splice(f,1);break}d||F[c].pool.push(a)}}this.children.splice(this.children.indexOf(a),1)}else throw"melonJS (me.ObjectContainer): "+a+" The supplied entity must be a child of the caller "+this;};e.Pa=function(a,b){return this.ea(a,null,b)};
e.ea=function(a,b,c){var d,f;c=!0===c?!0:!1;!0===c&&(f=[]);for(var g=this.children.length,k;g--,k=this.children[g];)if((k.Aa||k.Gb)&&k.da)if(k instanceof H){if(d=k.ea(a,b,c),!c&&d)return d}else if(k!==a&&(!b||k.type===b)&&(d=k.w["collideWith"+a.Zc].call(k.w,a.w),0!==d.x||0!==d.y)){k.Tb.call(k,d,a);d.type=k.type;d.Td=k;if(!c)return d;f.push(d)}return c?f:null};
e.sort=function(a){if(null===this.na){if(!0===a)for(var b=this.children.length,c;b--,c=this.children[b];)c instanceof H&&c.sort(a);this.na=function(a){a.children.sort(a["_sort"+a.ab.toUpperCase()]);a.na=null;E.Xc()}.defer(this)}};e.H=function(){this.na&&(clearTimeout(this.na),this.na=null);for(var a=this.children.length,b;a--,b=this.children[a];)b.Wa||this.removeChild(b)};
e.update=function(){for(var a=!1,b=!1,c=qa,d,f,g,k=E.viewport,n=this.children.length,s;n--,s=this.children[n];)if(!c||s.gd){s.xa&&oa++;b=0<oa;if(d=s.visible&&!b)f=s.pos.x,g=s.pos.y,G.pos.add(s.pos),G.set(G.pos,s.width,s.height);var D;if(D=s.visible)!b&&(b=s.Sa)&&(b=G,b=b.left<k.right&&k.left<b.right&&b.top<k.bottom&&k.top<b.bottom),D=b;s.Aa=D;a|=(s.Aa||s.Gb)&&s.update();d&&G.translate(-f,-g);0<oa&&oa--}return a};
e.i=function(a,b){var c=E.viewport,d=!1;a.save();a.globalAlpha*=this.alpha;a.translate(this.pos.x,this.pos.y);for(var f=this.children.length,g;f--,g=this.children[f];)d=g.xa,(g.Aa||d)&&g.Pb&&(!0===d&&(a.save(),a.translate(c.screenX-this.pos.x,c.screenY-this.pos.y)),g.i(a,b),!0===d&&a.restore());a.restore()};var ra=Math.min,sa=Math.max;function ta(a,b,c,d,f,g){t.call(this,new u(a,b),c-a,d-b);this.Ya=new u(f||this.width,g||this.height);this.offset=new u;this.target=null;this.lb=this.B.NONE;this.u={Ob:0,duration:0,axis:this.B.La,$a:null,start:0};this.r={color:0,alpha:0,duration:0,v:null};this.q={color:0,alpha:1,duration:0,v:null};a=this.height/6;this.fa=new u(~~((this.width-this.width/6)/2),~~((this.height-a)/2-0.25*a));this.fb=this.width-this.fa.x;this.eb=this.height-this.fa.y;this.update(!0)}h(ta,t);
e=ta.prototype;e.B={NONE:0,Ab:1,Bb:2,La:3};e.Ya=null;e.target=null;e.lb=0;e.Xb=!1;e.u=null;e.q=null;e.r=null;e.fb=0;e.eb=0;e.Db=0;e.Cb=0;e.screenX=0;e.screenY=0;function ua(a,b){var c=a.pos.x;b.x-a.pos.x>a.fb?a.pos.x=~~ra(b.x-a.fb,a.Db):b.x-a.pos.x<a.fa.x&&(a.pos.x=~~sa(b.x-a.fa.x,0));return c!==a.pos.x}function va(a,b){var c=a.pos.y;b.y-a.pos.y>a.eb?a.pos.y=~~ra(b.y-a.eb,a.Cb):b.y-a.pos.y<a.fa.y&&(a.pos.y=~~sa(b.y-a.fa.y,0));return c!==a.pos.y}
e.reset=function(a,b){this.pos.x=a||0;this.pos.y=b||0;this.lb=this.target=null};
e.update=function(a){var b=!1;if(this.target&&a)switch(this.lb){case this.B.Ab:b=ua(this,this.target);break;case this.B.Bb:b=va(this,this.target);break;case this.B.La:b=ua(this,this.target),b=va(this,this.target)||b}if(!0===this.Xb){if(A-this.u.start>=this.u.duration)this.Xb=!1,this.offset.set(0,0),"function"===typeof this.u.$a&&this.u.$a();else{if(this.u.axis===this.B.La||this.u.axis===this.B.Ab)this.offset.x=(Math.random()-0.5)*this.u.Ob;if(this.u.axis===this.B.La||this.u.axis===this.B.Bb)this.offset.y=
(Math.random()-0.5)*this.u.Ob}b=!0}!0===b&&l.event.oa(l.event.pc,[this.pos]);if(null!=this.q.v||null!=this.r.v)b=!0;return b};e.fadeOut=function(a,b,c){this.r.color=a;this.r.duration=b||1E3;this.r.alpha=1;this.r.v=(new l.oc(this.r)).yb({alpha:0},this.r.duration).$a(c||null);this.r.v.start()};e.fadeIn=function(a,b,c){this.q.color=a;this.q.duration=b||1E3;this.q.alpha=0;this.q.v=(new l.oc(this.q)).yb({alpha:1},this.q.duration).$a(c||null);this.q.v.start()};
e.i=function(a){this.q.v&&(a.globalAlpha=this.q.alpha,l.h.Ib(a,wa(this.q.color)),a.globalAlpha=1,1===this.q.alpha&&(this.q.v=null));this.r.v&&(a.globalAlpha=this.r.alpha,l.h.Ib(a,wa(this.r.color)),a.globalAlpha=1,0===this.r.alpha&&(this.r.v=null));l.h.yd()};var E={L:null,W:!1,Ga:null,A:!0,viewport:null,va:null,o:null,k:null,qb:!0,ab:"z",p:null,rd:0,ld:1,zb:2,jd:3,sb:null,Dc:function(a,b){E.W||(a=a||l.h.width,b=b||l.h.height,E.viewport=new ta(0,0,a,b),E.k=new H(0,0,a,b),E.k.name="rootContainer",E.L=l.h.Hd(),l.event.oa(l.event.nd),E.A=!0,E.W=!0)},reset:function(){E.Wc();E.viewport&&E.viewport.reset();E.L.setTransform(1,0,0,1,0,0);E.o={pos:{x:0,y:0}}},Hc:function(a){E.k.ca=!1;E.o=a;var b=E,c=E.o,d,f=null;d="collision".trim().toLowerCase();for(var g=c.m.length;g--;)if(c.m[g].name.toLowerCase().contains(d)){f=
c.m[g];break}d.toLowerCase().contains(xa)&&null==f&&(f=new l.kd(E.o.width,E.o.height));b.va=f;E.va&&E.va.ia||console.error("WARNING : no collision map detected");b=E.o.m;for(c=b.length;c--;)b[c].visible&&E.add(b[c]);b=E.viewport;c=Math.max(E.o.width,E.viewport.width);d=Math.max(E.o.height,E.viewport.height);b.Ya.set(c,d);b.Db=b.Ya.x-b.width;b.Cb=b.Ya.y-b.height;b=E.k;c=E.o.Z;for(d=0;d<c.length;d++){f=c[d];!1===E.qb&&(b=new H,b.name=f.name,b.visible=f.visible,b.z=f.z,x(b,f.opacity),b.ca=!1);for(g=
0;g<f.$.length;g++){var k=f.$[g];if(k=ka(k.name,k.x,k.y,k))k.z=f.z,k.visible=!0===f.visible,!0===E.qb&&!0===k.Pb&&(x(k,k.alpha*f.opacity),null!==k.g&&x(k.g,k.g.alpha*f.opacity)),pa(b,k)}!1===E.qb&&(pa(E.k,b),b.ca=!0)}E.k.sort(!0);E.k.ca=!0;E.o.pos.x!==E.o.pos.y&&E.L.translate(E.o.pos.x,E.o.pos.y);E.sb&&E.sb.call(E.sb,a.name);l.event.oa(l.event.od,[a.name])},add:function(a,b){"undefined"!==typeof b&&(a.z=b);pa(E.k,a)},Ed:function(a){return E.k.ya("name",a)},Dd:function(a){a=E.k.ya("GUID",a);return 0<
a.length?a[0]:null},ya:function(a,b){return E.k.ya(a,b)},Fd:function(a){return a.C},remove:function(a,b){a.C&&(!0===b?a.C.removeChild(a):(a.visible=a.Aa=!1,E.Ga=function(a){"undefined"!==typeof a.C&&a.C.removeChild(a);E.Ga=null}.defer(a)))},Wc:function(){E.Ga&&(clearTimeout(E.Ga),E.Ga=null);E.k.H()},sort:function(){E.k.sort()},Pa:function(a,b){return E.k.Pa(a,b)},ea:function(a,b,c){return E.k.ea(a,b,c)},Xc:function(){E.A=!0},update:function(){E.A=E.k.update()||E.A;E.A=E.viewport.update(E.A)||E.A;
return E.A},i:function(){E.A&&(E.viewport.screenX=E.viewport.pos.x+~~E.viewport.offset.x,E.viewport.screenY=E.viewport.pos.y+~~E.viewport.offset.y,E.L.save(),E.L.translate(-E.viewport.screenX,-E.viewport.screenY),E.viewport.screenX-=E.o.pos.x,E.viewport.screenY-=E.o.pos.y,E.k.i(E.L,E.viewport),E.L.restore(),E.viewport.i(E.L));E.A=!1}};var A=0,aa=1;var I={},J={},ya={},K=null,za=null,Aa=0;function Ba(a,b){if(3<Aa++){var c="melonJS: failed loading "+a;if(!1===la)I.disable(),b&&b(),console.log(c+", disabling audio");else throw c;}else J[a].load()}function Ca(a){za=a}I.Wd=function(a,b){if(3<Aa++){var c="melonJS: failed loading "+a;if(!1===la)I.disable(),b&&b(),console.log(c+", disabling audio");else throw c;}else J[a].load()};I.enable=function(){I.dd()};I.disable=function(){I.Jc()};
I.load=function(a,b,c){for(var d=[],f=0;f<I.uc.length;f++)d.push(a.src+a.name+"."+I.uc[f]+C.la);d=new window.Howl({urls:d,volume:window.Howler.volume(),onend:function(a){ya[a]&&(ya[a](),ya[a]=null)},onloaderror:function(){Ba.call(I,a.name,c)},onload:function(){Aa=0;b&&b()}});J[a.name]=d;return 1};l.wd.play=function(a,b,c,d){if((a=J[a.toLowerCase()])&&"undefined"!==typeof a)return a.loop(b||!1),a.volume("number"===typeof d?d.Q(0,1):window.Howler.volume()),a.play(null,c),a};
I.stop=function(a,b){var c=J[a.toLowerCase()];c&&"undefined"!==typeof c&&c.stop(b)};I.pause=function(a,b){var c=J[a.toLowerCase()];c&&"undefined"!==typeof c&&c.pause(b)};I.Ud=function(a,b){K=a.toLowerCase();return I.play(K,!0,navigator.isCocoonJS&&!window.Howler.usingWebAudio?Ca:void 0,b)};I.Xd=function(){null!==K&&(J[K].stop(navigator.isCocoonJS&&!window.Howler.usingWebAudio?za:void 0),K=null)};I.Qc=function(){null!==K&&J[K].pause(navigator.isCocoonJS&&!window.Howler.usingWebAudio?za:void 0)};
I.Wb=function(){null!==K&&J[K].play(null,navigator.isCocoonJS&&!window.Howler.usingWebAudio?Ca:void 0)};I.Cd=function(){return K};I.Vd=function(a){window.Howler.volume(a)};I.Id=function(){return window.Howler.volume()};I.mute=function(a){(a=J[a.toLowerCase()])&&"undefined"!==typeof a&&a.mute(!0)};I.unmute=function(a){I.mute(a,!1)};I.Jc=function(){window.Howler.mute()};I.dd=function(){window.Howler.unmute()};I.unload=function(a){a=a.toLowerCase();if(!(a in J))return!1;J[a].unload();delete J[a];return!0};
I.ac=function(){for(var a in J)J.hasOwnProperty(a)&&I.unload(a)};(function(){for(var a=0,b=["ms","moz","webkit","o"],c=window.requestAnimationFrame,d=window.cancelAnimationFrame,f=0;f<b.length&&(!c||!d);++f)c=window[b[f]+"RequestAnimationFrame"],d=window[b[f]+"CancelAnimationFrame"]||window[b[f]+"CancelRequestAnimationFrame"];c&&d||(c=function(b){var c=Date.now(),d=Math.max(0,16-(c-a)),f=window.setTimeout(function(){b(c+d)},d);a=c+d;return f},d=function(a){window.clearTimeout(a)});window.requestAnimationFrame=c;window.cancelAnimationFrame=d})();
var Da=-1,qa=!1,Ea={};function Fa(){Ga();window.addEventListener("blur",function(){qa=!0;I.Qc();l.event.oa(l.event.td)},!1);window.addEventListener("focus",function(){I.Wb();l.event.oa(l.event.ud)},!1)}function Ha(a){a&&I.Wb()}function Ga(){var a=new na;Ea[0]={};Ea[0].screen=a;Ea[0].transition=!0};function Ia(a){this.Ea=a;this.z=0;this.name=null;this.b=this.c=this.rows=this.cols=0;this.f=null;this.m=[];this.Z=[];this.W=!1;this.orientation=this.version="";this.f=null;w.call(this,new u,0,0)}h(Ia,w);Ia.prototype.reset=function(){if(!0===this.W){var a;for(a=this.m.length;a--;)this.m[a].reset(),this.m[a]=null;for(a=this.Z.length;a--;)this.Z[a].reset(),this.Z[a]=null;this.f=null;this.m.length=0;this.Z.length=0;this.pos.set(0,0);this.W=!1}};var L={},Ja=[],Ka=0;function La(a){void 0===L[a]&&(L[a]=new Ia(a),L[a].name=a,Ja.push(a))}
function ha(a){a=a.toString().toLowerCase();if(void 0===L[a])throw"melonJS: level "+a+" not found";if(L[a]instanceof Ia){var b=-1!==Da;b&&(window.cancelAnimationFrame(Da),Da=-1);E.reset();ea=0;L[Ja[Ka]]&&L[Ja[Ka]].reset();var c=L[a],d=m;if(!c.W){if("xml"===C.Cc(c.Ea)){null===d.Ma&&(d.Ma=new Ma);d.a=d.Ma.a;var d=d.Ma,f=C.Ua(c.Ea);if(!f)throw"melonJS:"+c.Ea+" TMX map not found";var g=0;d.a.setData(f);for(var f=d.a.zc(),k=0;k<f.length;k++)switch(f.item(k).nodeName){case "map":var n=f.item(k);c.version=
d.a.j(n,Na);c.orientation=d.a.j(n,Oa);c.cols=d.a.d(n,M);c.rows=d.a.d(n,N);c.c=d.a.d(n,Pa);c.b=d.a.d(n,Qa);c.width=c.cols*c.c;c.height=c.rows*c.b;c.ta=d.a.j(n,Ra);c.z=g++;O(c,n);c.P=c.ta?c.ta:c.P;c.P&&c.m.push(new l.dc("background_color",c.P,g++));c.jb&&c.m.push(new P("background_image",c.width,c.height,c.jb,g++));null!==E.p&&Sa(c)||(E.p=d.za(c));break;case "tileset":c.f||(c.f=new Ta);c.f.add(d.wb(f.item(k)));break;case Ua:c.m.push(d.tb(c,f.item(k),g++));break;case "layer":c.m.push(d.ub(c,f.item(k),
g++));break;case Va:c.Z.push(d.vb(c,f.item(k),g++))}d.a.xc()}else null===d.cb&&(d.cb=new Q),Wa(d.cb,c,C.Ua(c.Ea));if(c.width<E.viewport.width||c.height<E.viewport.height)d=~~((E.viewport.width-c.width)/2),g=~~((E.viewport.height-c.height)/2),c.pos.add({x:0<d?d:0,y:0<g?g:0});c.W=!0}Ka=Ja.indexOf(a);E.Hc(L[a]);b&&Ha.defer()}else throw"melonJS: no level loader defined";};function Q(){}
function Wa(a,b,c){if(!c)throw"melonJS:"+b.Ea+" TMX map not found";var d=0;b.version=c[Na];b.orientation=c[Oa];b.cols=parseInt(c[M],10);b.rows=parseInt(c[N],10);b.c=parseInt(c[Pa],10);b.b=parseInt(c[Qa],10);b.width=b.cols*b.c;b.height=b.rows*b.b;b.ta=c[Ra];b.z=d++;R(b,c);b.P=b.ta?b.ta:b.P;b.P&&b.m.push(new l.dc("background_color",b.P,d++));b.jb&&b.m.push(new P("background_image",b.width,b.height,b.jb,d++));null!==E.p&&Sa(b)||(E.p=a.za(b));b.f||(b.f=new Ta);c.tilesets.forEach(function(c){b.f.add(a.wb(c))});c.layers.forEach(function(c){switch(c.type){case Ua:b.m.push(a.tb(b,
c,d++));break;case Xa:b.m.push(a.ub(b,c,d++));break;case Va:b.Z.push(a.vb(b,c,d++))}})}Q.prototype.ub=function(a,b,c){a=new Ya(a.c,a.b,a.orientation,a.f,c);a.U(b);a.ia||(Sa(a)?a.p=E.p:(c=m.za(a),a.p=c));this.xb(a,b[Za],"json",null);return a};Q.prototype.tb=function(a,b,c){a=new P(b[S],parseInt(b[M],10)*a.c,parseInt(b[N],10)*a.b,b[T],c);a.visible=b[U];x(a,parseFloat(b[V]));R(a,b);"number"===typeof a.n&&(a.n=new u(parseFloat(a.n),parseFloat(a.n)));return a};
Q.prototype.wb=function(a){var b=new $a;b.U(a);return b};Q.prototype.vb=function(a,b,c){var d=new ab;d.U(b[S],b,a.f,c);return d};var xa="collision",S="name",Na="version",Oa="orientation",M="width",N="height",V="opacity",Pa="tilewidth",Qa="tileheight",Za="data",T="image",U="visible",Xa="tilelayer",Ua="imagelayer",Va="objectgroup",M="width",N="height",Ra="backgroundcolor";function Ta(){this.f=[]}Ta.prototype.add=function(a){this.f.push(a)};function bb(a,b){for(var c=-1,d=0,f=a.f.length;d<f;d++){if(a.f[d].contains(b))return a.f[d];a.f[d].I===a.f[d].Qb&&b>=a.f[d].I&&(c=d)}if(-1!==c)return a.f[c];throw"no matching tileset found for gid "+b;};function cb(a,b,c,d,f){t.call(this,new u(a*c,b*d),c,d);this.O=f;this.J=0!==(this.O&db);this.K=0!==(this.O&eb);this.Ra=0!==(this.O&fb);this.Lb=this.J||this.K||this.Ra;this.O&=~(db|eb|fb)}h(cb,t);function Ya(a,b,c,d,f){w.call(this,new u(0,0),0,0);this.c=a;this.b=b;this.orientation=c;this.F=(this.f=d)?this.f.f[0]:null;this.z=f}h(Ya,w);e=Ya.prototype;e.ka=null;
e.V=function(a){this.name=m.a.j(a,S);this.visible=1===m.a.d(a,U,1);this.cols=m.a.d(a,M);this.rows=m.a.d(a,N);x(this,m.a.mb(a,V,1));this.width=this.cols*this.c;this.height=this.rows*this.b;O(this,a);"undefined"===typeof this.D&&(this.D=!1);if(this.ia=this.name.toLowerCase().contains(xa))this.visible=!1;!0===this.D&&(this.Ca=l.h.Jb(this.cols*this.c,this.rows*this.b),this.Da=l.h.Nb(this.Ca))};
e.U=function(a){this.name=a[S];this.visible=a[U];this.cols=parseInt(a[M],10);this.rows=parseInt(a[N],10);x(this,parseFloat(a[V]));this.width=this.cols*this.c;this.height=this.rows*this.b;R(this,a);"undefined"===typeof this.D&&(this.D=!1);if(this.ia=this.name.toLowerCase().contains(xa))this.visible=!1;!0===this.D&&(this.Ca=l.h.Jb(this.cols*this.c,this.rows*this.b),this.Da=l.h.Nb(this.Ca))};e.reset=function(){this.D&&(this.Da=this.Ca=null);this.f=this.F=this.ka=this.p=null};
function gb(a,b,c){a.ka=[];for(var d=0;d<b;d++){a.ka[d]=[];for(var f=0;f<c;f++)a.ka[d][f]=null}}function hb(a,b,c,d){d=new cb(b,c,a.c,a.b,d);a.F.contains(d.O)?d.F=a.F:d.F=a.F=bb(a.f,d.O);return a.ka[b][c]=d}e.update=function(){return!1};
e.i=function(a,b){if(this.D){var c=Math.min(b.width,this.width),d=Math.min(b.height,this.height);this.Da.globalAlpha=a.globalAlpha*this.alpha;a.drawImage(this.Ca,b.pos.x,b.pos.y,c,d,b.pos.x,b.pos.y,c,d)}else{c=a.globalAlpha;a.globalAlpha*=this.alpha;var d=this.p,f=new u(b.pos.x/d.c,b.pos.y/d.b);f.x=~~f.x;f.y=~~f.y;var g=new u((b.pos.x+b.width+d.c)/d.c,(b.pos.y+b.height+d.b)/d.b);g.x=Math.ceil(g.x);g.y=Math.ceil(g.y);g.x=g.x>d.cols?d.cols:g.x;g.y=g.y>d.rows?d.rows:g.y;for(var k=f.y;k<g.y;k++)for(var n=
f.x;n<g.x;n++){var s=this.ka[n][k];s&&d.ga(a,n,k,s,s.F)}a.globalAlpha=c}};function ib(a,b,c,d){this.cols=a;this.rows=b;this.c=c;this.b=d}function Sa(a){var b=E.p;return"orthogonal"===a.orientation&&b.cols===a.cols&&b.rows===a.rows&&b.c===a.c&&b.b===a.b}function jb(a){"number"===typeof a.M&&(a.y-=a.height)}ib.prototype.ga=function(a,b,c,d,f){f.ga(a,f.ba.x+b*this.c,f.ba.y+(c+1)*this.b-f.b,d)};function kb(){}e=kb.prototype;e.name=null;e.x=0;e.y=0;e.width=0;e.height=0;e.z=0;e.M=void 0;e.ja=!1;e.Ba=!1;e.Ha=void 0;
e.V=function(a,b,c){this.name=m.a.j(a,S);this.x=m.a.d(a,"x");this.y=m.a.d(a,"y");this.z=c;this.width=m.a.d(a,M,0);this.height=m.a.d(a,N,0);this.M=m.a.d(a,"gid",null);this.Ba=this.ja=this.Va=!1;if(this.M)lb(this,b);else if(a.getElementsByTagName("ellipse").length)this.Va=!0;else if(b=a.getElementsByTagName("polygon"),b.length?this.ja=!0:(b=a.getElementsByTagName("polyline"),b.length&&(this.Ba=!0)),b.length){this.Ha=[];b=m.a.j(b[0],"points").split(" ");c=0;for(var d;c<b.length;c++)d=b[c].split(","),
this.Ha.push(new u(+d[0],+d[1]))}jb(this);O(this,a)};
e.U=function(a,b,c){this.name=a[S];this.x=parseInt(a.x,10);this.y=parseInt(a.y,10);this.z=parseInt(c,10);this.width=parseInt(a[M]||0,10);this.height=parseInt(a[N]||0,10);this.M=parseInt(a.gid,10)||null;this.Ba=this.ja=this.Va=!1;if(this.M)lb(this,b);else if(void 0!==a.ellipse)this.Va=!0;else if(b=a.polygon,void 0!==b?this.ja=!0:(b=a.polyline,void 0!==b&&(this.Ba=!0)),void 0!==b){this.Ha=[];var d=this;b.forEach(function(a){d.Ha.push(new u(parseInt(a.x,10),parseInt(a.y,10)))})}jb(this);R(this,a)};
function lb(a,b){var c=bb(b,a.M);a.width=c.c;a.height=c.b;a.Yb=a.width;var d=new cb(a.x,a.y,c.c,c.b,a.M),f=l.h.Nb(l.h.Jb(c.c,c.b));c.ga(f,0,0,d);a.e=f.canvas};function ab(){}e=ab.prototype;e.name=null;e.width=0;e.height=0;e.visible=!1;e.z=0;e.$=[];e.V=function(a,b,c,d){this.name=a;this.width=m.a.d(b,M);this.height=m.a.d(b,N);this.visible=1===m.a.d(b,U,1);this.opacity=m.a.mb(b,V,1).Q(0,1);this.z=d;this.$=[];b.firstChild&&"properties"===b.firstChild.nextSibling.nodeName&&O(this,b);a=b.getElementsByTagName("object");for(b=0;b<a.length;b++){var f=new kb;f.V(a[b],c,d);this.$.push(f)}};
e.U=function(a,b,c,d){var f=this;this.name=a;this.width=b[M];this.height=b[N];this.visible=b[U];this.opacity=parseFloat(b[V]||1).Q(0,1);this.z=d;this.$=[];R(this,b);b.objects.forEach(function(a){var b=new kb;b.U(a,c,d);f.$.push(b)})};e.reset=function(){this.$=null};function P(a,b,c,d,f,g){this.name=a;this.e=d?C.Ta(mb(d)):null;if(!this.e)throw"melonJS: '"+d+"' file for Image Layer '"+this.name+"' not found!";this.T=this.e.width;this.N=this.e.height;a=E.viewport;b=b?Math.min(a.width,b):a.width;c=c?Math.min(a.height,c):a.height;w.call(this,new u(0,0),b,c);this.z=f;this.n=new u(1,1);g&&("number"===typeof g?this.n.set(g,g):v(this.n,g));this.Xa=a.pos.Oa();this.xa=!0;this.gb="repeat";this.Ja=this.Ia=!0;Object.defineProperty(this,"repeat",{get:function(){return this.gb},
set:function(a){this.gb=a;switch(this.gb){case "no-repeat":this.Ja=this.Ia=!1;break;case "repeat-x":this.Ia=!0;this.Ja=!1;break;case "repeat-y":this.Ia=!1;this.Ja=!0;break;default:this.Ja=this.Ia=!0}}});this.s.set(0,0);this.handle=l.event.ad(l.event.pc,this.fd.bind(this))}h(P,w);e=P.prototype;e.reset=function(){this.handle&&(l.event.ed(this.handle),this.handle=null);this.Xa=this.e=null};
e.fd=function(a){if(0!==this.n.x||0!==this.n.y)this.pos.x+=(a.x-this.Xa.x)*this.n.x%this.T,this.pos.x=(this.T+this.pos.x)%this.T,this.pos.y+=(a.y-this.Xa.y)*this.n.y%this.N,this.pos.y=(this.N+this.pos.y)%this.N,v(this.Xa,a)};e.update=function(){return!1};
e.i=function(a,b){a.save();0===this.s.y&&0===this.s.x||a.translate(~~(this.s.x*(this.viewport.width-this.T)),~~(this.s.y*(this.viewport.height-this.N)));a.globalAlpha*=this.alpha;var c,d;if(0===this.n.x&&0===this.n.y)c=Math.min(b.width,this.T),d=Math.min(b.height,this.N),a.drawImage(this.e,b.left,b.top,c,d,b.left,b.top,c,d);else{var f=~~this.pos.x,g=~~this.pos.y,k=0,n=0;c=Math.min(this.T-f,this.width);d=Math.min(this.N-g,this.height);do{do a.drawImage(this.e,f,g,c,d,k,n,c,d),g=0,n+=d,d=Math.min(this.N,
this.height-n);while(this.Ja&&n<this.height);k+=c;if(!this.Ia||k>=this.width)break;f=0;c=Math.min(this.T,this.width-k);g=~~this.pos.y;n=0;d=Math.min(this.N-~~this.pos.y,this.height)}while(1)}a.restore()};e.H=function(){this.reset()};var db=2147483648,eb=1073741824,fb=536870912;function $a(){this.nc=[];this.Zb=[];this.$b=[]}e=$a.prototype;e.type={kc:"solid",ic:"platform",hc:"lslope",jc:"rslope",fc:"ladder",mc:"topladder",cc:"breakable"};
e.V=function(a){this.I=m.a.d(a,"firstgid");var b=m.a.j(a,"source");if(b){b=mb(b);a=C.Ua(b);if(!a)throw"melonJS:"+b+" TSX tileset not found";m.a.parseFromString(a);a=m.a.Ac("tileset")}this.name=m.a.j(a,S);this.c=m.a.d(a,Pa);this.b=m.a.d(a,Qa);this.t=m.a.d(a,"spacing",0);this.margin=m.a.d(a,"margin",0);this.ba=new u(0,0);b=a.getElementsByTagName("tileoffset");0<b.length&&(this.ba.x=m.a.d(b[0],"x"),this.ba.y=m.a.d(b[0],"y"));for(var b=a.getElementsByTagName("tile"),c=0;c<b.length;c++){var d=m.a.d(b[c],
"id")+this.I,f={};O(f,b[c]);nb(this,d,f)}(b=(c=a.getElementsByTagName(T)[0].getAttribute("source"))?C.Ta(mb(c)):null)||console.log("melonJS: '"+c+"' file for tileset '"+this.name+"' not found!");a=a.getElementsByTagName(T)[0].getAttribute("trans");ob(this,b,a)};
e.U=function(a){this.I=a.firstgid;var b=a.source;if(b&&(b=mb(b),a=C.Ua(b),!a))throw"melonJS:"+b+" TSX tileset not found";this.name=a[S];this.c=parseInt(a[Pa],10);this.b=parseInt(a[Qa],10);this.t=parseInt(a.spacing||0,10);this.margin=parseInt(a.margin||0,10);this.ba=new u(0,0);if(b=a.tileoffset)this.ba.x=parseInt(b.x,10),this.ba.y=parseInt(b.y,10);var b=a.tileproperties,c;for(c in b){var d={},f=d,g=b[c],k=void 0;for(k in g)void 0===f[k]&&(f[k]=g[k]);nb(this,parseInt(c,10)+this.I,d)}(b=(c=mb(a[T]))?
C.Ta(c):null)||console.log("melonJS: '"+c+"' file for tileset '"+this.name+"' not found!");ob(this,b,a.trans||null)};function ob(a,b,c){b&&(a.e=b,a.ob=~~((a.e.width-a.margin)/(a.c+a.t)),a.hd=~~((a.e.height-a.margin)/(a.b+a.t)));a.Qb=a.I+(a.ob*a.hd-1||0);null!==c&&a.e&&(a.e=l.h.tc(a.e,"transparent",c.toUpperCase()).canvas)}
function nb(a,b,c){c.Pd=c.type?c.type.toLowerCase()===a.type.kc:!1;c.Nd=c.type?c.type.toLowerCase()===a.type.ic:!1;c.Fc=c.type?c.type.toLowerCase()===a.type.hc:!1;c.Gc=c.type?c.type.toLowerCase()===a.type.jc:!1;c.Kd=c.type?c.type.toLowerCase()===a.type.cc:!1;c.Md=c.type?c.type.toLowerCase()===a.type.fc:!1;c.Rd=c.type?c.type.toLowerCase()===a.type.mc:!1;c.Od=c.Fc||c.Gc;c.Ld=!!c.type;a.nc[b]=c}e.contains=function(a){return a>=this.I&&a<=this.Qb};
function pb(a,b){var c=a.Zb[b];"undefined"===typeof c&&(c=a.Zb[b]=a.margin+b%a.ob*(a.t+a.c));return c}function qb(a,b){var c=a.$b[b];"undefined"===typeof c&&(c=a.$b[b]=a.margin+(a.t+a.b)*~~(b/a.ob));return c}
e.ga=function(a,b,c,d){if(d.Lb){var f=1,g=0,k=0,n=1,s=b,D=c;b=c=0;a.save();d.Ra&&(f=0,k=g=1,n=0,D+=this.b-this.c);d.J&&(f=-f,k=-k,s+=d.Ra?this.b:this.c);d.K&&(g=-g,n=-n,D+=d.Ra?this.c:this.b);a.transform(f,g,k,n,s,D)}f=d.O-this.I;a.drawImage(this.e,pb(this,f),qb(this,f),this.c,this.b,b,c,this.c,this.b);d.Lb&&a.restore()};function rb(a){var b;(b=!a)||(b=a,b=null!==b&&("true"===b.trim()||"false"===b.trim()));if(b)a=a?"true"===a:!0;else if(null!==a&&!isNaN(a)&&""!==a.trim())a=Number(a);else if(a.match(/^json:/i)){b=a.split(/^json:/i)[1];try{a=JSON.parse(b)}catch(c){throw"Unable to parse JSON: "+b;}}return a}function O(a,b){var c=b.getElementsByTagName("properties")[0];if(c)for(var c=c.getElementsByTagName("property"),d=0;d<c.length;d++){var f=m.a.j(c[d],S),g=m.a.j(c[d],"value");a[f]=rb(g)}}
function R(a,b){var c=b.properties;if(c)for(var d in c)c.hasOwnProperty(d)&&(a[d]=rb(c[d]))};function Ma(){this.a||(this.a=new sb)}e=Ma.prototype;e.a=null;e.ub=function(a,b,c){a=new Ya(a.c,a.b,a.orientation,a.f,c);a.V(b);b=b.getElementsByTagName(Za)[0];c=this.a.j(b,"encoding",null);var d=this.a.j(b,"compression",null);""===c&&(c=null);""===d&&(d=null);if(!a.ia)if(Sa(a))a.p=E.p;else{var f=m.za(a);a.p=f}this.xb(a,b,c,d);return a};
e.tb=function(a,b,c){var d=this.a.j(b,S),f=this.a.d(b,M),g=this.a.d(b,N),k=b.getElementsByTagName(T)[0].getAttribute("source");a=new P(d,f*a.c,g*a.b,k,c);a.visible=1===this.a.d(b,U,1);x(a,this.a.mb(b,V,1));O(a,b);"number"===typeof a.n&&(a.n=new u(parseFloat(a.n),parseFloat(a.n)));return a};e.wb=function(a){var b=new $a;b.V(a);return b};e.vb=function(a,b,c){var d=this.a.j(b,S),f=new ab;f.V(d,b,a.f,c);return f};
e.za=function(a){switch(a.orientation){case "orthogonal":return new ib(a.cols,a.rows,a.c,a.b);case "isometric":return new l.lc(a.cols,a.rows,a.c,a.b);default:throw"melonJS: "+a.orientation+" type TMX Tile Map not supported!";}};
e.xb=function(a,b,c,d){gb(a,a.cols,a.rows);switch(c){case null:b=b.getElementsByTagName("tile");break;case "json":break;case "csv":case "base64":for(var f="",g=0,k=b.childNodes.length;g<k;g++)f+=b.childNodes[g].nodeValue;"csv"===c?b=tb(f,a.cols):(b=ub(f),null!==d&&(b=vb()));break;default:throw"melonJS: TMX Tile Map "+c+" encoding not supported!";}for(f=d=0;f<a.rows;f++)for(g=0;g<a.cols;g++)k=null==c?this.a.d(b[d++],"gid"):b[d++],0!==k&&(k=hb(a,g,f,k),a.visible&&a.D&&a.p.ga(a.Da,g,f,k,k.F))};function wb(){}e=wb.prototype;e.Ma=null;e.cb=null;e.a=null;e.za=function(a){switch(a.orientation){case "orthogonal":return new ib(a.cols,a.rows,a.c,a.b);case "isometric":return new l.lc(a.cols,a.rows,a.c,a.b);default:throw"melonJS: "+a.orientation+" type TMX Tile Map not supported!";}};
e.xb=function(a,b,c,d){gb(a,a.cols,a.rows);switch(c){case null:b=b.getElementsByTagName("tile");break;case "json":break;case "csv":case "base64":for(var f="",g=0,k=b.childNodes.length;g<k;g++)f+=b.childNodes[g].nodeValue;"csv"===c?b=tb(f,a.cols):(b=ub(f),null!==d&&(b=vb()));break;default:throw"melonJS: TMX Tile Map "+c+" encoding not supported!";}for(f=d=0;f<a.rows;f++)for(g=0;g<a.cols;g++)k=null==c?this.a.d(b[d++],"gid"):b[d++],0!==k&&(k=hb(a,g,f,k),a.visible&&a.D&&a.p.ga(a.Da,g,f,k,k.F))};
function sb(){return{ra:null,setData:function(a){this.ra=a},Ac:function(a){return this.ra?this.ra.getElementsByTagName(a)[0]:null},zc:function(){return this.ra?this.ra.getElementsByTagName("*"):null},j:function(a,b,c){return(a=a.getAttribute(b))?a.trim():c},d:function(a,b,c){return(a=this.j(a,b,c))?parseInt(a,10):c},mb:function(a,b,c){return(a=this.j(a,b,c))?parseFloat(a):c},Bd:function(a,b,c){return(a=this.j(a,b,c))?"true"===a:c},xc:function(){this.ra=null}}};var yb={vc:function(a){a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");if(xb)return window.atob(a);for(var b=[],c,d,f,g,k,n=0;n<a.length;)c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),c=
c<<2|d>>4,d=(d&15)<<4|g>>2,f=(g&3)<<6|k,b.push(String.fromCharCode(c)),64!==g&&b.push(String.fromCharCode(d)),64!==k&&b.push(String.fromCharCode(f));return b=b.join("")}},zb={},ea=0,Ab=/^.*(\\|\/|\:)/,Bb=/\.[^\.]*$/;function ub(a){var b;b=4;a=yb.vc(a);var c,d,f,g;g="function"===typeof window.vd?new Uint32Array(a.length/b):[];c=0;for(f=a.length/b;c<f;c++)for(g[c]=0,d=b-1;0<=d;--d)g[c]+=a.charCodeAt(c*b+d)<<(d<<3);return g}
function vb(){throw"melonJS: GZIP/ZLIB compressed TMX Tile Map not supported!";}function tb(a,b){a=a.trim().split("\n");for(var c=[],d=0;d<a.length;d++)for(var f=a[d].split(",",b),g=0;g<f.length;g++)c.push(+f[g]);return c}function mb(a){return a.replace(Ab,"").replace(Bb,"")}function Cb(a){return a.substring(a.lastIndexOf(".")+1,a.length)}
function wa(a){if("#"!==a.charAt(0))return a;a=a.substring(1,a.length);if(null==zb[a]){var b,c,d;6>a.length?(b=a.charAt(0)+a.charAt(0),c=a.charAt(1)+a.charAt(1),d=a.charAt(2)+a.charAt(2)):(b=a.substring(0,2),c=a.substring(2,4),d=a.substring(4,6));zb[a]=parseInt(b,16)+","+parseInt(c,16)+","+parseInt(d,16)}return"rgb("+zb[a]+")"};var C={},W={},X={},Y={},Db={},Z={},Eb=0,Fb=0,Gb=0;C.Hb=function(){Fb===Eb?C.onload?(clearTimeout(Gb),setTimeout(function(){C.onload();l.event.oa(l.event.pd)},300)):console.error("no load callback defined"):Gb=setTimeout(C.Hb,100)};C.Tc=function(a,b,c){W[a.name]=new Image;W[a.name].onload=b;W[a.name].onerror=c;W[a.name].src=a.src+C.la};
C.Vc=function(a,b,c){var d=new XMLHttpRequest,f=Cb(a.src).toLowerCase();d.overrideMimeType&&("json"===f?d.overrideMimeType("application/json"):d.overrideMimeType("text/xml"));d.open("GET",a.src+C.la,!0);"tmx"===a.type&&La(a.name);d.ontimeout=c;d.onreadystatechange=function(){if(4===d.readyState)if(200===d.status||0===d.status&&d.responseText){var g=null;switch(f){case "xml":case "tmx":g=Hb.match(/msie/i)||!d.responseXML?(new DOMParser).parseFromString(d.responseText,"text/xml"):d.responseXML;f="xml";
break;case "json":g=JSON.parse(d.responseText);break;default:throw"melonJS: TMX file format "+f+"not supported !";}X[a.name]={data:g,Qd:"tmx"===a.type,format:f};b()}else c()};d.send(null)};C.Uc=function(a,b,c){var d=new XMLHttpRequest;d.overrideMimeType&&d.overrideMimeType("application/json");d.open("GET",a.src+C.la,!0);d.ontimeout=c;d.onreadystatechange=function(){4===d.readyState&&(200===d.status||0===d.status&&d.responseText?(Z[a.name]=JSON.parse(d.responseText),b()):c())};d.send(null)};
C.Sc=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a.src+C.la,!0);d.responseType="arraybuffer";d.onerror=c;d.onload=function(){var c=d.response;if(c){for(var c=new Uint8Array(c),g=[],k=0;k<c.byteLength;k++)g[k]=String.fromCharCode(c[k]);Y[a.name]=g.join("");b()}};d.send()};C.la="";C.onload=void 0;C.Ub=void 0;C.Pc=function(){Fb++;var a=C.Bc();C.Ub&&C.Ub(a);l.event.oa(l.event.gc,[a])};C.Mc=function(a){throw"melonJS: Failed loading resource "+a.src;};
C.Yc=function(){var a=document.location.href.match(/\?nocache/)||!1;C.la=a?"?"+parseInt(1E7*Math.random(),10):""};C.preload=function(a){for(var b=0;b<a.length;b++)Eb+=C.load(a[b],C.Pc.bind(C),C.Mc.bind(C,a[b]));C.Hb()};
C.load=function(a,b,c){a.name=a.name.toLowerCase();switch(a.type){case "binary":return C.Sc(a,b,c),1;case "image":return C.Tc(a,b,c),1;case "json":return C.Uc(a,b,c),1;case "tmx":case "tsx":return C.Vc(a,b,c),1;case "audio":if(I.Jd())return I.load(a,b,c),1;break;default:throw"melonJS: me.loader.load : unknown or invalid resource type : "+a.type;}return 0};
C.unload=function(a){a.name=a.name.toLowerCase();switch(a.type){case "binary":if(!(a.name in Y))return!1;delete Y[a.name];return!0;case "image":if(!(a.name in W))return!1;"function"===typeof W[a.name].wc&&W[a.name].wc();delete W[a.name];return!0;case "json":if(!(a.name in Z))return!1;delete Z[a.name];return!0;case "tmx":case "tsx":if(!(a.name in X))return!1;delete X[a.name];return!0;case "audio":return I.unload(a.name);default:throw"melonJS: me.loader.unload : unknown or invalid resource type : "+
a.type;}};C.ac=function(){for(var a in Y)C.unload(a);for(a in W)C.unload(a);for(a in X)C.unload(a);for(a in Db)C.unload(a);for(a in Z)C.unload(a);I.ac()};C.Cc=function(a){a=a.toLowerCase();return a in X?X[a].format:null};C.Ua=function(a){a=a.toLowerCase();return a in X?X[a].data:null};C.Ad=function(a){a=a.toLowerCase();return a in Y?Y[a]:null};C.Ta=function(a){a=a.toLowerCase();return a in W?W[a]:null};C.Gd=function(a){a=a.toLowerCase();return a in Z?Z[a]:null};C.Bc=function(){return Fb/Eb};var Hb=navigator.userAgent,r=!1,xb="function"===typeof window.atob;var Ib=!1,Jb=!1,Kb=!1,Lb=[];function $(){if(!Kb){if(!document.body)return setTimeout($,13);document.removeEventListener?document.removeEventListener("DOMContentLoaded",$,!1):window.removeEventListener("load",$,!1);Kb=!0;for(var a=0;a<Lb.length;a++)Lb[a].call(window,[]);Lb.length=0}}
window.Oc=function(a){Jb||(Jb=!0,"complete"===document.readyState?$():(document.addEventListener&&document.addEventListener("DOMContentLoaded",$,!1),window.addEventListener("load",$,!1)));Kb?a.call(window,[]):Lb.push(function(){return a.call(window,[])})};window.Oc(function(){window.rc()});"function"!==typeof Object.create&&(Object.create=function(a){function b(){}b.prototype=a;return new b});
if(!Function.prototype.bind){var Mb=function(){};Function.prototype.bind=function(a){function b(){if(this instanceof b){var f=c.apply(this,d.concat(Array.prototype.slice.call(arguments)));return Object(f)===f?f:this}return c.apply(a,d.concat(Array.prototype.slice.call(arguments)))}var c=this;if("function"!==typeof c)throw new TypeError("Function.prototype.bind called on incompatible "+c);var d=Array.prototype.slice.call(arguments,1);c.prototype&&(Mb.prototype=c.prototype,b.prototype=new Mb,Mb.prototype=
null);return b}}window.bd||(window.bd=function(a,b,c){var d=Date.now(),f;"boolean"!==typeof b&&(b=!1);return function(){var g=Date.now(),k=g-d,n=arguments;if(k<a)!1===b&&(clearTimeout(f),f=setTimeout(function(){d=g;return c.apply(null,n)},k));else return d=g,c.apply(null,n)}});"undefined"===typeof Date.now&&(Date.now=function(){return(new Date).getTime()});"undefined"===typeof console&&(console={log:function(){},info:function(){},error:function(){alert(Array.prototype.slice.call(arguments).join(", "))}});
Function.prototype.defer=function(){var a=this,b=Array.prototype.slice.call(arguments);return window.setTimeout(function(){return a.apply(a,b)},0.01)};window.throttle||(window.throttle=function(a,b,c){var d=Date.now(),f;"boolean"!==typeof b&&(b=!1);return function(){var g=Date.now(),k=g-d,n=arguments;if(k<a)!1===b&&(clearTimeout(f),f=setTimeout(function(){d=g;return c.apply(null,n)},k));else return d=g,c.apply(null,n)}});
String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+window/,"")});String.prototype.contains=function(a){return-1<this.indexOf(a)};Number.prototype.Q=function(a,b){return this<a?a:this>b?b:+this};Number.prototype.random=function(a,b){return~~(Math.random()*(b-a+1))+a};Array.prototype.remove=function(a){a=Array.prototype.indexOf.call(this,a);-1!==a&&Array.prototype.splice.call(this,a,1);return this};
Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=0,d=this.length;d--;c++)a.call(b||this,this[c],c,this)});
window.rc=function(){if(!Ib){I.zd();navigator.Rc=navigator.Rc||navigator.msPointerEnabled;navigator.Ic=navigator.Ic||navigator.Sd||0;window.yc=window.yc||window.qd;Hb.match(/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone|Mobi/i);try{r="undefined"!==typeof window.localStorage}catch(a){r=!1}p.qc();C.Yc();A=Date.now();m=new wb;Fa();ja("me.ObjectEntity",B);ja("me.CollectableEntity",ia);ja("me.LevelEntity",ga);Ib=!0}};
